name: Pull detached upstream automatically

on:
  workflow_dispatch:
  schedule:
    # Run twice per week
    - cron: '22 2 * * 2,6'
  
jobs:
  check_upstream:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      # Checkout this repo
      - uses: actions/checkout@v2
      # Fetch the history and unshallow the checked out repo so that it can be used
      - name: Fetch all history for all tags and branches
        run: git fetch --prune --unshallow
      # Pull the detached remote and do the magic
      - name: Pull Detached Remote
        uses: litetex/pull-detached-remote@v0.2
        with:
          upstreamrepo: https://github.com/xvmconfigs/xvm_default_config
          upstreambranch: master
          prassignees: litetex
          prlabels: upstream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_PAT: ${{ secrets.GH_PAT }}
